name: GitHub Action Demo
# on: [push]
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
      - "feature/*"

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
      - run: echo "Hello, world 2!"
