name: GitHub Action Demo
# on: [push]

env:
  MY_NAME: "Worasalid"
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main
      - "feature"
      - "feature/*"

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world!"
      - run: echo ${{ env.MY_NAME }}}

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - run: echo "test job!"
      - run: echo My Repo is ${{ github.repository }}
      - run: echo My Repo VAR is ${{ vars.REPOSITORY_NAME }}

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - run: echo "deploy job!"
      - run: echo db password is ${{ secrets.DB_PASSWORD }}
